name: Build and publish python package
on:
  # this allows us to trigger manually
  # Note: we are not automatically publishing to pypi anymore. This workflow is retained
  # for now so that we can manually publish if we desired to do so.
  workflow_dispatch:


jobs:
  find-latest:
    # Find latest tag and published package versions
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.tag.outputs.latest_tag }}
      latest_published: ${{ steps.package.outputs.latest_published }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: tag
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      - name: Check latest package version
        id: package
        run: |
          echo "latest_published=v$(curl https://pypi.org/pypi/opensafely-matching/json | jq -r 'last(.releases | to_entries[] | select(.key).key)')" >> "$GITHUB_OUTPUT"

  build-and-publish-package:
    runs-on: ubuntu-latest
    name: Build and publish PyPI package
    needs: find-latest
    if: needs.find-latest.outputs.latest_tag != needs.find-latest.outputs.latest_published
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install wheel package
      run: |
        pip install wheel
    - name: Generate correct value for VERSION file
      run: |
        echo ${{ needs.find-latest.outputs.latest_tag }} > osmatching/VERSION
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc  # v1.90
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
