---
name: Tag new version

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: tag-new-version-group

jobs:
  ci:
    uses: ./.github/workflows/main.yaml

  tag-new-version:
    needs: [ci]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v7
      - name: Tag new version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
