name: Tests

on: [push]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run checks

    steps:
      - uses: actions/checkout@v4
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.8"
      - name: Set up development environment
        run: just devenv
      - name: Check formatting and linting rules
        run: just check

  test:
    runs-on: ubuntu-latest
    name: Run test suite

    steps:
      - uses: actions/checkout@v4
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.8"
      - name: Set up development environment
        run: just devenv
      - name: Run tests
        run: just test

  test-opensafely:
    runs-on: ubuntu-latest
    name: Run test suite with opensafely
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install opensafely
        run: pip install opensafely
      - name: Run tests with opensafely
        run: opensafely exec python:v2 pytest

  test-package-build:
    runs-on: ubuntu-latest
    name: Test we can build PyPI package
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install wheel package
      run: |
        pip install wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
